# Default values for eksdemo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Release-wide Values
replicas: 2
version: 'latest'


image:
  tag: latest
  repository: 474054470595.dkr.ecr.us-east-1.amazonaws.com/helmp-ecrdo-1j78l7mo8l18w
  imagePullPolicy: Always
