# Default values for eksdemo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Release-wide Values
replicas: 1
version: 'latest'

# Service Specific Values
frontend:
  image: 474054470595.dkr.ecr.us-east-1.amazonaws.com/devel-ecrdo-rdbs11ku8lqm
